name: Deploy

on:
  push:
    branches: [ master ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: TestRelease

